import type { DocType } from './types';
import { LAYOUT_FIELDTYPES, TABLE_FIELDTYPES, scalarType } from './fieldMap';
import { pascalCase, slugify } from './util';

// Columns every persisted doctype row carries (the Frappe document base).
const BASE_BLOCKS = [
  '  "name" text',
  '  "owner" text',
  '  "creation" timestamptz',
  '  "modified" timestamptz',
  '  "modified_by" text',
  '  "docstatus" smallint NOT NULL DEFAULT 0',
  '  "idx" integer NOT NULL DEFAULT 0',
];
const CHILD_BLOCKS = ['  "parent" text', '  "parenttype" text', '  "parentfield" text'];

const BASE_NAMES = new Set(['name', 'owner', 'creation', 'modified', 'modified_by', 'docstatus', 'idx']);
const CHILD_NAMES = new Set(['parent', 'parenttype', 'parentfield']);

export interface ChildRef {
  field: string;
  target: string;
  included: boolean;
}

export interface GenResult {
  doctype: string;
  table: string;
  pascal: string;
  istable: boolean;
  submittable: boolean;
  autoname: string;
  sourcePath: string;
  totalFields: number;
  scalarCount: number;
  childRefs: ChildRef[];
  sql: string;
  tsInterface: string;
}

export function generateOne(dt: DocType, inSlice: Set<string>, sourcePath: string): GenResult {
  const table = slugify(dt.name);
  const pascal = pascalCase(dt.name);
  const istable = dt.istable === 1;
  const submittable = dt.is_submittable === 1;
  const src = sourcePath.replace(/\\/g, '/');

  const seen = new Set<string>(BASE_NAMES);
  if (istable) CHILD_NAMES.forEach((n) => seen.add(n));

  const colBlocks: string[] = [...BASE_BLOCKS, ...(istable ? CHILD_BLOCKS : [])];
  const tsLines: string[] = [];
  const childRefs: ChildRef[] = [];
  let scalarCount = 0;

  for (const f of dt.fields) {
    const ft = f.fieldtype;
    if (!ft || LAYOUT_FIELDTYPES.has(ft)) continue;
    const fn = f.fieldname;
    if (!fn) continue;

    // Child relationship -> separate table, not a column.
    if (TABLE_FIELDTYPES.has(ft)) {
      const target = (f.options || '').trim();
      const included = inSlice.has(target);
      childRefs.push({ field: fn, target, included });
      if (included) tsLines.push(`  ${fn}?: ${pascalCase(target)}[];`);
      continue;
    }

    if (seen.has(fn)) continue;
    seen.add(fn);
    scalarCount++;

    // --- SQL column ---
    let ddl: string;
    if (ft === 'Check') {
      ddl = `  "${fn}" boolean NOT NULL DEFAULT ${f.default === '1' ? 'true' : 'false'}`;
    } else {
      ddl = `  "${fn}" ${scalarType(ft).pg}`;
    }
    let comment = '';
    if (ft === 'Link' || ft === 'Dynamic Link') {
      comment = `  -- ${ft} -> ${f.options || '?'}`;
    } else if (ft === 'Select' && f.options) {
      const vals = f.options.split('\n').map((s) => s.trim()).filter(Boolean).join(' | ');
      if (vals) comment = `  -- Select: ${vals}`;
    }
    colBlocks.push(comment ? `${comment}\n${ddl}` : ddl);

    // --- TS field ---
    let tsType: string;
    if (ft === 'Select' && f.options) {
      const opts = f.options.split('\n').map((s) => s.trim());
      const hasBlank = opts.length > 0 && opts[0] === '';
      const vals = opts.filter(Boolean).map((v) => `'${v.replace(/'/g, "\\'")}'`);
      tsType = vals.length ? vals.join(' | ') + (hasBlank ? " | ''" : '') : 'string';
    } else {
      tsType = scalarType(ft).ts;
    }
    const linkNote = ft === 'Link' || ft === 'Dynamic Link' ? ` // -> ${f.options || '?'}` : '';
    tsLines.push(`  ${fn}${f.reqd ? '' : '?'}: ${tsType};${linkNote}`);
  }

  const body = colBlocks.join(',\n') + ',\n  PRIMARY KEY ("name")';
  const sql = `-- ${dt.name}  (source: ${src})
-- istable=${istable ? 1 : 0} is_submittable=${submittable ? 1 : 0} autoname=${dt.autoname || ''} json_fields=${dt.fields.length} scalar_cols=${scalarCount}
CREATE TABLE IF NOT EXISTS "${table}" (
${body}
);`;

  const baseIface = istable ? 'ChildDoc' : 'BaseDoc';
  const tsInterface = `/** ${dt.name} — generated from ${src} */
export interface ${pascal} extends ${baseIface} {
${tsLines.join('\n')}
}`;

  return {
    doctype: dt.name,
    table,
    pascal,
    istable,
    submittable,
    autoname: dt.autoname || '',
    sourcePath: src,
    totalFields: dt.fields.length,
    scalarCount,
    childRefs,
    sql,
    tsInterface,
  };
}

export function buildMigration(results: GenResult[]): string {
  const tablesRev = results.map((r) => `"${r.table}"`).reverse().join(', ');
  const header = `-- =====================================================================
-- Migration 0001 — Selling slice  (GENERATED by src/generator — DO NOT EDIT)
-- Source of truth: ERPNext DocType JSON. Regenerate with: npm run generate
-- Rollback:
--   DROP TABLE IF EXISTS ${tablesRev} CASCADE;
-- Notes:
--   * Idempotent (CREATE TABLE IF NOT EXISTS). Adding NEW columns to an
--     existing table is NOT handled yet (generator v1) — drop & recreate in dev.
--   * Link fields are plain text (no FK constraint in v1); target is in a comment.
--   * reqd is enforced in the TS/controller layer, not as NOT NULL (rows may be drafts).
-- =====================================================================
`;
  return header + '\n' + results.map((r) => r.sql).join('\n\n') + '\n';
}

export function buildTypes(results: GenResult[]): string {
  const header = `/* =====================================================================
 * Generated DocType interfaces — Selling slice  (DO NOT EDIT)
 * Source of truth: ERPNext DocType JSON. Regenerate: npm run generate
 * ===================================================================== */

export interface BaseDoc {
  name: string;
  owner?: string;
  creation?: string;
  modified?: string;
  modified_by?: string;
  docstatus?: 0 | 1 | 2;
  idx?: number;
}

export interface ChildDoc extends BaseDoc {
  parent?: string;
  parenttype?: string;
  parentfield?: string;
}
`;
  return header + '\n' + results.map((r) => r.tsInterface).join('\n\n') + '\n';
}

export function buildMeta(results: GenResult[]): string {
  const map: Record<string, unknown> = {};
  for (const r of results) {
    map[r.doctype] = {
      doctype: r.doctype,
      table: r.table,
      istable: r.istable,
      submittable: r.submittable,
      autoname: r.autoname,
      childTables: r.childRefs
        .filter((c) => c.included)
        .map((c) => ({ field: c.field, doctype: c.target, table: slugify(c.target) })),
    };
  }
  const header = `/* =====================================================================
 * Generated DocType runtime metadata  (DO NOT EDIT)
 * Drives the document runtime (table names, child tables, submittable).
 * Regenerate: npm run generate
 * ===================================================================== */

export interface ChildTableMeta {
  field: string;
  doctype: string;
  table: string;
}

export interface DocMeta {
  doctype: string;
  table: string;
  istable: boolean;
  submittable: boolean;
  autoname: string;
  childTables: ChildTableMeta[];
}

export const META: Record<string, DocMeta> = `;
  return header + JSON.stringify(map, null, 2) + ';\n';
}
